from .base import Level
from .navigation import NAVIGATION_LEVEL
from .file_ops import (
    DIRECTORY_CREATION_LEVEL,
    FILE_COPY_LEVEL,
    FILE_DELETION_LEVEL,
    FILE_APPEND_LEVEL
)
from .advanced import FILE_MOVE_LEVEL, COMMAND_ARGS_LEVEL

__all__ = [
    'Level',
    'NAVIGATION_LEVEL',
    'DIRECTORY_CREATION_LEVEL',
    'FILE_COPY_LEVEL',
    'FILE_DELETION_LEVEL',
    'FILE_APPEND_LEVEL',
    'FILE_MOVE_LEVEL',
    'COMMAND_ARGS_LEVEL'
]

ALL_LEVELS = [
    NAVIGATION_LEVEL,
    DIRECTORY_CREATION_LEVEL,
    FILE_COPY_LEVEL,
    FILE_DELETION_LEVEL,
    FILE_APPEND_LEVEL,
    FILE_MOVE_LEVEL,
    COMMAND_ARGS_LEVEL
] 